### ISSUE TITLE
Slow search

### ISSUE THREAD

**Issue by AdrianRamzes** [Muetze42/hellofresh-database#1]
First of all - Thanks for creating this database!

I didn't look into the code but it looks like the search is a blocking action. It works weird - looks like it waits for URL to be updated.
The user can't really type as some input characters can be skipped and it's super laggy.

**Comment by Muetze42** [comment]
For me it works as intended. In which country and with which browser does this appear?

**Comment by AdrianRamzes** [comment]
CH and accessed from Switzerland.

**Comment by Muetze42** [comment]
So for me, the search runs as intended, even in Switzerland.

The data comes from the database and there is therefore a debounce of 300ms so that the server is not flooded.
 Is possibly that meant?

**Comment by AdrianRamzes** [comment]
I think it's not about the delay in server response but more about some race condition while typing.
What is happening is that the search input is updated after getting response from server - that leads to some weird behaviour. Try to type longer names and see that some times input is changed by it self back to some prev state.
I think the server response should be ignored if it's a response to the search term that is no longer valid.
For example:
1) user types 'a' (current text input: a)
2) the app calls server with _?s=a_
3) user types 'b' (current text input: ab)
4) server returns response for _?s=a_
    4a) **URL is changed**
    4b) **text input is updated to 'a'**
5) User types 'c' (current text input is 'ac' - **which is incorrect** expected: 'abc')

I didn't check the code but I'm almost sure that this is the case.

**Comment by Muetze42** [comment]
I got the domain hfresh.info and for this a newer version of the database is planned.

Is it possible to live with the problem so long that I do not have to touch the old code?

**Comment by AdrianRamzes** [comment]
Sure. Lol I don't care that much :P
Just take a look into this when implementing the newer version.
