### ISSUE TITLE
Add HelloFresh Spain

### ISSUE THREAD

**Issue by Laesx** [Muetze42/hellofresh-database#43]
Hello I would like to have the Spanish HelloFresh recipes in the db, I haven't looked into it myself but I imagine it would be a pretty trivial thing to add. Otherwise I'll just code up something myself, thanks!

**Comment by Muetze42** [comment]
Sorry. I have a lot on my plate.

I have created Spain and just started the scraper.

Tonight (in about 6 hours) I will switch Spain live.

**Comment by Laesx** [comment]
> Sorry. I have a lot on my plate.
> 
> I have created Spain and just started the scraper.
> 
> Tonight (in about 6 hours) I will switch Spain live.

Don't worry, thank you!

**Comment by Muetze42** [comment]
OK. Spain is live.
